// <auto-generated />
using System;
using EventTicketing.DataAccess.Concrete.EntityFramework.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventTicketing.DataAccess.Migrations
{
    [DbContext(typeof(EventTicketingDbContext))]
    [Migration("20260826090145_AddUserAuthentication")]
    partial class AddUserAuthentication
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventTicketing.Domain.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_Email_Active")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("EventTicketing.Domain.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CancellationCutoffUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndsAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SalesEndUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("SalesStartUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("UX_Events_Slug_Active")
                        .HasFilter("[IsDeleted] = 0");

                    b.HasIndex("Status", "StartsAtUtc")
                        .HasDatabaseName("IX_Events_Status_StartsAt");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Status", "StartsAtUtc"), new[] { "Name", "VenueId" });

                    b.HasIndex("VenueId", "StartsAtUtc")
                        .HasDatabaseName("IX_Events_Venue_StartsAt");

                    b.ToTable("Events", null, t =>
                        {
                            t.HasCheckConstraint("CK_Events_CancellationCutoff", "[CancellationCutoffUtc] <= [StartsAtUtc]");

                            t.HasCheckConstraint("CK_Events_EndAfterStart", "[EndsAtUtc] > [StartsAtUtc]");

                            t.HasCheckConstraint("CK_Events_SalesWindow", "[SalesEndUtc] > [SalesStartUtc]");
                        });
                });

            modelBuilder.Entity("EventTicketing.Domain.Entities.EventSeat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BlockReason")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int>("EventSectionId")
                        .HasColumnType("int");

                    b.Property<long>("SeatId")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeatId");

                    b.HasIndex("EventId", "SeatId")
                        .IsUnique()
                        .HasDatabaseName("UX_EventSeats_Event_Seat");

                    b.HasIndex("EventId", "Status")
                        .HasDatabaseName("IX_EventSeats_Event_Status");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("EventId", "Status"), new[] { "SeatId", "EventSectionId" });

                    b.HasIndex("EventSectionId", "Status")
                        .HasDatabaseName("IX_EventSeats_Section_Status");

                    b.ToTable("EventSeats", (string)null);
                });

            modelBuilder.Entity("EventTicketing.Domain.Entities.EventSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<int?>("GeneralAdmissionCapacity")
                        .HasColumnType("int");

                    b.Property<bool>("IsOnSale")
                        .HasColumnType("bit");

                    b.Property<int>("SeatCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("VenueSectionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeatCategoryId");

                    b.HasIndex("VenueSectionId");

                    b.HasIndex("EventId", "VenueSectionId")
                        .IsUnique()
                        .HasDatabaseName("UX_EventSections_Event_VenueSection");

                    b.HasIndex("Id", "EventId")
                        .IsUnique()
                        .HasDatabaseName("AK_EventSections_Id_EventId");

                    b.ToTable("EventSections", null, t =>
                        {
                            t.HasCheckConstraint("CK_EventSections_GaCapacityPositive", "[GeneralAdmissionCapacity] IS NULL OR [GeneralAdmissionCapacity] > 0");
                        });
                });

            modelBuilder.Entity("EventTicketing.Domain.Entities.EventTicketPrice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("SeatCategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("ServiceFee")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SeatCategoryId");

                    b.HasIndex("EventId", "SeatCategoryId")
                        .IsUnique()
                        .HasDatabaseName("UX_EventTicketPrices_Event_Category")
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("EventTicketPrices", null, t =>
                        {
                            t.HasCheckConstraint("CK_EventTicketPrices_FeeNonNegative", "[ServiceFee] >= 0");

                            t.HasCheckConstraint("CK_EventTicketPrices_PriceNonNegative", "[Price] >= 0");
                        });
                });

            modelBuilder.Entity("EventTicketing.Domain.Entities.Organizer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Organizers", (string)null);
                });

            modelBuilder.Entity("EventTicketing.Domain.Entities.Seat", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("RowLabel")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("VenueSectionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VenueSectionId", "RowLabel", "SeatNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Seats_Section_Row_Number")
                        .HasFilter("[RowLabel] IS NOT NULL");

                    b.ToTable("Seats", (string)null);
                });

            modelBuilder.Entity("EventTicketing.Domain.Entities.SeatCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VenueId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UX_SeatCategories_Venue_Name");

                    b.ToTable("SeatCategories", (string)null);
                });

            modelBuilder.Entity("EventTicketing.Domain.Entities.Ticket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nchar(3)")
                        .IsFixedLength();

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<long?>("EventSeatId")
                        .HasColumnType("bigint");

                    b.Property<int>("EventSectionId")
                        .HasColumnType("int");

                    b.Property<decimal>("PricePaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PurchasedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<int>("SeatCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("SeatLabelSnapshot")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<decimal>("ServiceFeePaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("TicketNumber")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventSeatId")
                        .IsUnique()
                        .HasDatabaseName("UX_Tickets_ActiveSeat")
                        .HasFilter("[EventSeatId] IS NOT NULL AND [Status] = 1");

                    b.HasIndex("SeatCategoryId");

                    b.HasIndex("TicketNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_Tickets_TicketNumber");

                    b.HasIndex("EventId", "Status")
                        .HasDatabaseName("IX_Tickets_Event_Status");

                    b.HasIndex("EventSectionId", "Status")
                        .HasDatabaseName("IX_Tickets_EventSection_Status");

                    b.HasIndex("UserId", "PurchasedAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("IX_Tickets_User_PurchasedAt");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("UserId", "PurchasedAtUtc"), new[] { "EventId", "Status", "PricePaid", "TicketNumber" });

                    b.ToTable("Tickets", null, t =>
                        {
                            t.HasCheckConstraint("CK_Tickets_CancellationConsistency", "([Status] = 2 AND [CancelledAtUtc] IS NOT NULL) OR ([Status] <> 2 AND [CancelledAtUtc] IS NULL)");

                            t.HasCheckConstraint("CK_Tickets_PriceNonNegative", "[PricePaid] >= 0 AND [ServiceFeePaid] >= 0");
                        });
                });

            modelBuilder.Entity("EventTicketing.Domain.Entities.TicketStatusHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("ChangedAtUtc")
                        .HasColumnType("datetime2(3)");

                    b.Property<int?>("ChangedByUserId")
                        .HasColumnType("int");

                    b.Property<int?>("FromStatus")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<long>("TicketId")
                        .HasColumnType("bigint");

                    b.Property<int>("ToStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("TicketId", "ChangedAtUtc")
                        .HasDatabaseName("IX_TicketStatusHistory_Ticket_ChangedAt");

                    b.HasIndex("ToStatus", "ChangedAtUtc")
                        .HasDatabaseName("IX_TicketStatusHistory_ToStatus_ChangedAt");

                    b.ToTable("TicketStatusHistory", (string)null);
                });

            modelBuilder.Entity("EventTicketing.Domain.Entities.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Venues_Name_Active")
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("Venues", (string)null);
                });

            modelBuilder.Entity("EventTicketing.Domain.Entities.VenueSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAtUtc")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int?>("GeneralAdmissionCapacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SeatCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("SectionType")
                        .HasColumnType("int");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeatCategoryId");

                    b.HasIndex("Id", "VenueId")
                        .IsUnique()
                        .HasDatabaseName("AK_VenueSections_Id_VenueId");

                    b.HasIndex("VenueId", "Name")
                        .IsUnique()
                        .HasDatabaseName("UX_VenueSections_Venue_Name");

                    b.ToTable("VenueSections", null, t =>
                        {
                            t.HasCheckConstraint("CK_VenueSections_CapacityByType", "([SectionType] = 1 AND [GeneralAdmissionCapacity] IS NULL) OR ([SectionType] = 2 AND [GeneralAdmissionCapacity] > 0)");
                        });
                });

            modelBuilder.Entity("EventTicketing.Domain.Entities.Event", b =>
                {
                    b.HasOne("EventTicketing.Domain.Entities.Organizer", "Organizer")
                        .WithMany("Events")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventTicketing.Domain.Entities.Venue", "Venue")
                        .WithMany("Events")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organizer");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("EventTicketing.Domain.Entities.EventSeat", b =>
                {
                    b.HasOne("EventTicketing.Domain.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventTicketing.Domain.Entities.EventSection", "EventSection")
                        .WithMany("EventSeats")
                        .HasForeignKey("EventSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventTicketing.Domain.Entities.Seat", "Seat")
                        .WithMany("EventSeats")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("EventSection");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("EventTicketing.Domain.Entities.EventSection", b =>
                {
                    b.HasOne("EventTicketing.Domain.Entities.Event", "Event")
                        .WithMany("EventSections")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventTicketing.Domain.Entities.SeatCategory", "SeatCategory")
                        .WithMany()
                        .HasForeignKey("SeatCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventTicketing.Domain.Entities.VenueSection", "VenueSection")
                        .WithMany("EventSections")
                        .HasForeignKey("VenueSectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("SeatCategory");

                    b.Navigation("VenueSection");
                });

            modelBuilder.Entity("EventTicketing.Domain.Entities.EventTicketPrice", b =>
                {
                    b.HasOne("EventTicketing.Domain.Entities.Event", "Event")
                        .WithMany("TicketPrices")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventTicketing.Domain.Entities.SeatCategory", "SeatCategory")
                        .WithMany()
                        .HasForeignKey("SeatCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("SeatCategory");
                });

            modelBuilder.Entity("EventTicketing.Domain.Entities.Seat", b =>
                {
                    b.HasOne("EventTicketing.Domain.Entities.VenueSection", "VenueSection")
                        .WithMany("Seats")
                        .HasForeignKey("VenueSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VenueSection");
                });

            modelBuilder.Entity("EventTicketing.Domain.Entities.SeatCategory", b =>
                {
                    b.HasOne("EventTicketing.Domain.Entities.Venue", "Venue")
                        .WithMany("SeatCategories")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("EventTicketing.Domain.Entities.Ticket", b =>
                {
                    b.HasOne("EventTicketing.Domain.Entities.Event", "Event")
                        .WithMany("Tickets")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventTicketing.Domain.Entities.EventSeat", "EventSeat")
                        .WithMany("Tickets")
                        .HasForeignKey("EventSeatId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EventTicketing.Domain.Entities.EventSection", "EventSection")
                        .WithMany("Tickets")
                        .HasForeignKey("EventSectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventTicketing.Domain.Entities.SeatCategory", "SeatCategory")
                        .WithMany()
                        .HasForeignKey("SeatCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventTicketing.Domain.Entities.AppUser", "User")
                        .WithMany("Tickets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("EventSeat");

                    b.Navigation("EventSection");

                    b.Navigation("SeatCategory");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EventTicketing.Domain.Entities.TicketStatusHistory", b =>
                {
                    b.HasOne("EventTicketing.Domain.Entities.AppUser", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EventTicketing.Domain.Entities.Ticket", "Ticket")
                        .WithMany("StatusHistory")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("EventTicketing.Domain.Entities.VenueSection", b =>
                {
                    b.HasOne("EventTicketing.Domain.Entities.SeatCategory", "SeatCategory")
                        .WithMany("VenueSections")
                        .HasForeignKey("SeatCategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EventTicketing.Domain.Entities.Venue", "Venue")
                        .WithMany("Sections")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SeatCategory");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("EventTicketing.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("EventTicketing.Domain.Entities.Event", b =>
                {
                    b.Navigation("EventSections");

                    b.Navigation("TicketPrices");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("EventTicketing.Domain.Entities.EventSeat", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("EventTicketing.Domain.Entities.EventSection", b =>
                {
                    b.Navigation("EventSeats");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("EventTicketing.Domain.Entities.Organizer", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("EventTicketing.Domain.Entities.Seat", b =>
                {
                    b.Navigation("EventSeats");
                });

            modelBuilder.Entity("EventTicketing.Domain.Entities.SeatCategory", b =>
                {
                    b.Navigation("VenueSections");
                });

            modelBuilder.Entity("EventTicketing.Domain.Entities.Ticket", b =>
                {
                    b.Navigation("StatusHistory");
                });

            modelBuilder.Entity("EventTicketing.Domain.Entities.Venue", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("SeatCategories");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("EventTicketing.Domain.Entities.VenueSection", b =>
                {
                    b.Navigation("EventSections");

                    b.Navigation("Seats");
                });
#pragma warning restore 612, 618
        }
    }
}
